services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    networks:
      - app-network

  admin:
    build:
      context: ./admin
    ports:
      - "3001:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

